name: ğŸ Generate Snake

on:
  # cháº¡y 2 láº§n/ngÃ y
  schedule:
    - cron: "0 */12 * * *"
  # cho phÃ©p cháº¡y tay
  workflow_dispatch:
  # cháº¡y khi báº¡n cáº­p nháº­t README láº§n Ä‘áº§u
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Táº¡o áº£nh snake tá»« lá»‹ch sá»­ commit cá»§a user
      - name: Generate snake svgs
        uses: Platane/snk@v3
        with:
          github_user_name: minhducant
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # (tuá»³ chá»n) LÆ°u artifact kiá»ƒm tra
      - uses: actions/upload-artifact@v4
        with:
          name: snake-artifact
          path: dist

      # Deploy áº£nh lÃªn nhÃ¡nh gh-pages Ä‘á»ƒ nhÃºng vÃ o README
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
